//! Core data types for the skill subsystem.
//!
//! Defines [`PlatformSkill`], [`DomainSkill`], [`Skill`], [`SkillMetadata`],
//! and inherent methods for accessing skill metadata.

use derive_builder::Builder;
use serde::{Deserialize, Serialize};

/// A skill defined and pre-installed by the Carisa platform core.
///
/// Platform skills are managed internally by the core and cannot
/// be registered from external domain code.
///
/// The `always_load` flag signals that this skill should be loaded
/// automatically into every agent session without being requested
/// explicitly via the catalog.
#[derive(Builder, Debug, Clone, Serialize, Deserialize)]
#[builder(pattern = "owned")]
pub struct PlatformSkill {
    /// Unique identifier for this skill (e.g. `"coder"`).
    id: String,
    /// Human-readable title (e.g. `"Expert Coder"`).
    title: String,
    /// Short description shown in the skill catalog.
    description: String,
    /// Full instructions injected into the agent context when loaded.
    instructions: String,
    /// If `true`, this skill loads automatically into every agent session.
    always_load: bool,
}

impl PlatformSkill {
    /// Returns the skill's unique identifier.
    pub fn id(&self) -> &str {
        &self.id
    }

    /// Returns the human-readable title.
    pub fn title(&self) -> &str {
        &self.title
    }

    /// Returns the short description.
    pub fn description(&self) -> &str {
        &self.description
    }

    /// Returns the full instructions string.
    pub fn instructions(&self) -> &str {
        &self.instructions
    }

    /// Returns `true` if this skill should be auto-loaded into every
    /// agent session.
    pub(crate) const fn always_load(&self) -> bool {
        self.always_load
    }
}

/// A skill defined by a domain developer or loaded from markdown.
///
/// Constructed using [`DomainSkillBuilder`] (generated by
/// `derive_builder`).
#[derive(Builder, Debug, Clone, Serialize, Deserialize)]
#[builder(pattern = "owned")]
pub struct DomainSkill {
    /// Unique identifier for this skill (e.g. `"my-custom-skill"`).
    pub(crate) id: String,
    /// Human-readable title (e.g. `"My Custom Skill"`).
    pub(crate) title: String,
    /// Short description shown in the skill catalog.
    pub(crate) description: String,
    /// Full instructions injected into the agent context when loaded.
    pub(crate) instructions: String,
}

impl DomainSkill {
    /// Returns the skill's unique identifier.
    pub fn id(&self) -> &str {
        &self.id
    }

    /// Returns the human-readable title.
    pub fn title(&self) -> &str {
        &self.title
    }

    /// Returns the short description.
    pub fn description(&self) -> &str {
        &self.description
    }

    /// Returns the full instructions string.
    pub fn instructions(&self) -> &str {
        &self.instructions
    }
}

/// Homogeneous storage for platform and domain skills.
///
/// Wraps both [`PlatformSkill`] and [`DomainSkill`] into a single
/// type for storage in a single `HashMap`. Avoids dynamic dispatch
/// (`dyn Trait`) and its associated heap allocation.
#[derive(Debug, Clone)]
#[non_exhaustive]
pub enum Skill {
    /// A platform-defined skill (core-only).
    Platform(PlatformSkill),
    /// A user-defined or markdown-loaded skill.
    Domain(DomainSkill),
}

impl Skill {
    /// Returns the skill's unique identifier.
    pub fn id(&self) -> &str {
        match self {
            Self::Platform(p) => p.id(),
            Self::Domain(d) => d.id(),
        }
    }

    /// Returns the human-readable title.
    pub fn title(&self) -> &str {
        match self {
            Self::Platform(p) => p.title(),
            Self::Domain(d) => d.title(),
        }
    }

    /// Returns the short description.
    pub fn description(&self) -> &str {
        match self {
            Self::Platform(p) => p.description(),
            Self::Domain(d) => d.description(),
        }
    }

    /// Returns the full instructions string.
    pub fn instructions(&self) -> &str {
        match self {
            Self::Platform(p) => p.instructions(),
            Self::Domain(d) => d.instructions(),
        }
    }
}

/// Lightweight catalog entry containing only the id and description.
///
/// Skills where `always_load` is `true` are excluded from the catalog,
/// as they are loaded automatically and should not appear in the
/// user-facing catalog.
#[derive(Debug, Clone, Serialize)]
#[non_exhaustive]
pub struct SkillMetadata {
    /// Skill identifier.
    pub id: String,
    /// Short description.
    pub description: String,
}

#[cfg(test)]
mod tests {
    use super::*;
    use rstest::rstest;

    #[test]
    fn platform_skill_inherent_methods_return_values() {
        let skill = PlatformSkillBuilder::default()
            .id("ps1".to_owned())
            .title("Platform Title".to_owned())
            .description("Platform Desc".to_owned())
            .instructions("Platform Instructions".to_owned())
            .always_load(true)
            .build()
            .expect("all fields provided");
        assert_eq!(skill.id(), "ps1");
        assert_eq!(skill.title(), "Platform Title");
        assert_eq!(skill.description(), "Platform Desc");
        assert_eq!(skill.instructions(), "Platform Instructions");
        assert!(skill.always_load());
    }

    #[test]
    fn domain_skill_inherent_methods_return_values() {
        let skill = DomainSkillBuilder::default()
            .id("ds1".to_owned())
            .title("Domain Title".to_owned())
            .description("Domain Desc".to_owned())
            .instructions("Domain Instructions".to_owned())
            .build()
            .expect("all fields provided");
        assert_eq!(skill.id(), "ds1");
        assert_eq!(skill.title(), "Domain Title");
        assert_eq!(skill.description(), "Domain Desc");
        assert_eq!(skill.instructions(), "Domain Instructions");
    }

    #[test]
    fn domain_skill_has_no_always_load_field() {
        let skill = DomainSkillBuilder::default()
            .id("x".to_owned())
            .title("t".to_owned())
            .description("d".to_owned())
            .instructions("i".to_owned())
            .build()
            .expect("all fields provided");
        drop(skill);
    }

    #[test]
    fn skill_metadata_construction_and_access() {
        let meta = SkillMetadata {
            id: "test-id".to_owned(),
            description: "test-desc".to_owned(),
        };
        assert_eq!(meta.id, "test-id");
        assert_eq!(meta.description, "test-desc");
    }

    #[test]
    fn skill_enum_accepts_both_variants() {
        let platform = PlatformSkillBuilder::default()
            .id("p".to_owned())
            .title("t".to_owned())
            .description("d".to_owned())
            .instructions("i".to_owned())
            .always_load(false)
            .build()
            .expect("all fields provided");
        let domain = DomainSkillBuilder::default()
            .id("d".to_owned())
            .title("t".to_owned())
            .description("d".to_owned())
            .instructions("i".to_owned())
            .build()
            .expect("all fields provided");

        let p = Skill::Platform(platform);
        let d = Skill::Domain(domain);

        let desc = |s: &Skill| match s {
            Skill::Platform(ps) => ps.description().to_owned(),
            Skill::Domain(ds) => ds.description().to_owned(),
        };
        assert_eq!(desc(&p), "d");
        assert_eq!(desc(&d), "d");
    }

    /// T2-CP1: `PlatformSkillBuilder` with all fields produces Ok with
    /// correct values.
    #[test]
    fn platform_skill_builder_success() {
        let skill = PlatformSkillBuilder::default()
            .id("ps-core".to_owned())
            .title("Core Skill".to_owned())
            .description("A platform-level skill".to_owned())
            .instructions("Do X, then Y".to_owned())
            .always_load(true)
            .build()
            .expect("all required fields set");

        assert_eq!(skill.id, "ps-core");
        assert_eq!(skill.title, "Core Skill");
        assert_eq!(skill.description, "A platform-level skill");
        assert_eq!(skill.instructions, "Do X, then Y");
        assert!(skill.always_load);
    }

    /// T2-CP2: `DomainSkillBuilder` with all fields produces Ok with
    /// correct values.
    #[test]
    fn domain_skill_builder_success() {
        let skill = DomainSkillBuilder::default()
            .id("ds-custom".to_owned())
            .title("Custom Skill".to_owned())
            .description("A user-defined skill".to_owned())
            .instructions("Step 1: …".to_owned())
            .build()
            .expect("all required fields set");

        assert_eq!(skill.id, "ds-custom");
        assert_eq!(skill.title, "Custom Skill");
        assert_eq!(skill.description, "A user-defined skill");
        assert_eq!(skill.instructions, "Step 1: …");
    }

    /// T2-CP3..CP6: `DomainSkillBuilder` fails when any required field is
    /// missing. The error message must mention the missing field name.
    #[rstest]
    #[case::missing_id_returns_error(
        DomainSkillBuilder::default()
            .title("t".into())
            .description("d".into())
            .instructions("i".into()),
        "id"
    )]
    #[case::missing_title_returns_error(
        DomainSkillBuilder::default()
            .id("x".into())
            .description("d".into())
            .instructions("i".into()),
        "title"
    )]
    #[case::missing_description_returns_error(
        DomainSkillBuilder::default()
            .id("x".into())
            .title("t".into())
            .instructions("i".into()),
        "description"
    )]
    #[case::missing_instructions_returns_error(
        DomainSkillBuilder::default()
            .id("x".into())
            .title("t".into())
            .description("d".into()),
        "instructions"
    )]
    fn domain_skill_builder_requires_all_fields(
        #[case] builder: DomainSkillBuilder,
        #[case] field_name: &str,
    ) {
        let err = builder.build().unwrap_err();
        let msg = err.to_string();
        assert!(
            msg.contains(field_name),
            "Error for missing field '{field_name}' should mention \
             the field name, got: {msg}"
        );
    }

    /// T2-CP7: `PlatformSkillBuilder` without `always_load` fails.
    #[test]
    fn platform_skill_builder_requires_always_load() {
        let err = PlatformSkillBuilder::default()
            .id("p".to_owned())
            .title("t".to_owned())
            .description("d".to_owned())
            .instructions("i".to_owned())
            .build()
            .unwrap_err();
        let msg = err.to_string();
        assert!(
            msg.contains("always_load"),
            "Error for missing 'always_load' should mention \
             the field name, got: {msg}"
        );
    }
}
