//! Serializable types that form a session log.

use std::time::{SystemTime, UNIX_EPOCH};

use serde::{Deserialize, Serialize};

/// Unique identifier of a persisted message.
pub type MessageId = String;
/// Identifier of the agent that owns a session.
pub type AgentId = String;
/// Identifier of an agent session.
pub type SessionId = String;
/// Timestamp expressed as milliseconds since the Unix epoch.
pub type TimestampMillis = i64;

/// Message in the representation used by a storage backend.
///
/// The payload is intentionally opaque to migration. A cold backend must
/// preserve it without decoding or recompressing it.
#[derive(Clone, Debug, Deserialize, Serialize)]
#[non_exhaustive]
pub struct StoredLogMessage {
  /// Message identifier, kept outside the payload for indexing and deduplication.
  pub id: MessageId,
  /// Serialized message bytes in the backend's native format.
  pub payload: Vec<u8>,
}

/// Structured message stored in a session log.
#[non_exhaustive]
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct LogMessage {
  /// ULID of the message.
  pub id: MessageId,
  /// Agent that owns the message.
  pub agent_id: AgentId,
  /// Agent display name when the message was recorded.
  pub agent_nickname: String,
  /// Session that owns the message.
  pub session_id: SessionId,
  /// Message creation time.
  pub timestamp: TimestampMillis,
  /// Event-specific data.
  pub kind: LogMessageKind,
}

/// Data-free mirror of `LogMessageKind`, stored uncompressed so a
/// future search/filter trait can filter
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
#[non_exhaustive]
pub enum LogMessageKindTag {
  /// User message.
  User = 0,
  /// Assistant message.
  Assistant = 1,
  /// Assistant reasoning.
  Thinking = 2,
  /// Tool invocation.
  ToolCall = 3,
  /// Tool result.
  ToolResult = 4,
  /// Turn boundary.
  Turn = 5,
  /// Internal step.
  Step = 6,
  /// Condensed history.
  Condensation = 7,
}

impl LogMessageKindTag {
  /// Returns the stable byte representation of this tag.
  pub const fn as_u8(self) -> u8 {
    self as u8
  }

  /// Kept for the future search/filter trait, even though nothing
  /// calls it yet.
  pub const fn try_from_u8(value: u8) -> Option<Self> {
    match value {
      0 => Some(Self::User),
      1 => Some(Self::Assistant),
      2 => Some(Self::Thinking),
      3 => Some(Self::ToolCall),
      4 => Some(Self::ToolResult),
      5 => Some(Self::Turn),
      6 => Some(Self::Step),
      7 => Some(Self::Condensation),
      _ => None,
    }
  }
}

/// Event variants that can be part of a session history.
#[non_exhaustive]
#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum LogMessageKind {
  /// Entry written by the user.
  User {
    /// Text written by the user.
    content: String,
  },
  /// Text response from the assistant.
  Assistant {
    /// Text generated by the assistant.
    content: String,
    /// Provider that generated the response.
    provider: Option<String>,
    /// Model that generated the response.
    model: Option<String>,
    /// Provider response identifier.
    provider_response_id: Option<String>,
  },
  /// Reasoning associated with an assistant response.
  Thinking {
    /// Reasoning content.
    reasoning: StoredReasoning,
    /// Assistant message that owns this reasoning.
    parent_assistant_id: Option<MessageId>,
  },
  /// Tool call requested by the assistant.
  ToolCall {
    /// Tool name.
    tool_name: String,
    /// Tool arguments as JSON.
    arguments: serde_json::Value,
    /// Mensaje asistente al que pertenece.
    parent_assistant_id: Option<MessageId>,
    /// Associated execution step.
    step_id: Option<MessageId>,
  },
  /// Result produced by a tool call.
  ToolResult {
    /// Identifier of the related call message.
    tool_call_id: MessageId,
    /// Tool result as JSON.
    result: serde_json::Value,
    /// Whether the tool finished with an error.
    is_error: bool,
    /// Human-readable error description, if any.
    error_message: Option<String>,
  },
  /// Logical start or end of a turn.
  Turn {
    /// Turn number.
    turn_number: u32,
  },
  /// Internal step of a turn.
  Step {
    /// Step number within the turn.
    step_number: u32,
    /// Parent turn identifier.
    turn_id: MessageId,
  },
  /// Summary generated while condensing the history.
  Condensation {
    /// Summary text.
    summary: String,
    /// Model that generated the summary.
    model_used: Option<String>,
  },
}

impl LogMessageKind {
  // Kept for the future search/filter trait, even though nothing
  // calls it yet.
  /// Returns the data-free tag for this event kind.
  pub const fn tag(&self) -> LogMessageKindTag {
    match self {
      Self::User { .. } => LogMessageKindTag::User,
      Self::Assistant { .. } => LogMessageKindTag::Assistant,
      Self::Thinking { .. } => LogMessageKindTag::Thinking,
      Self::ToolCall { .. } => LogMessageKindTag::ToolCall,
      Self::ToolResult { .. } => LogMessageKindTag::ToolResult,
      Self::Turn { .. } => LogMessageKindTag::Turn,
      Self::Step { .. } => LogMessageKindTag::Step,
      Self::Condensation { .. } => LogMessageKindTag::Condensation,
    }
  }
}

/// Provider-independent representation of generated reasoning.
#[non_exhaustive]
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct StoredReasoning {
  /// Optional identifier assigned by the provider.
  pub id: Option<String>,
  /// Blocks that form the reasoning.
  pub content: Vec<StoredReasoningContent>,
}

/// Serializable reasoning block.
#[non_exhaustive]
#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(tag = "type", content = "value", rename_all = "snake_case")]
pub enum StoredReasoningContent {
  /// Visible reasoning text.
  Text {
    /// Text content.
    text: String,
    /// Optional provider signature.
    signature: Option<String>,
  },
  /// Opaque encrypted content.
  Encrypted(String),
  /// Content redacted by the provider.
  Redacted {
    /// Data preserved opaquely.
    data: String,
  },
  /// Reasoning summary.
  Summary(String),
}

/// Persistent metadata for a session.
#[non_exhaustive]
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct SessionMeta {
  /// Owning agent.
  pub agent_id: AgentId,
  /// Agent display name.
  pub agent_nickname: String,
  /// Session described by this metadata.
  pub session_id: SessionId,
  /// Creation time.
  pub created_at: TimestampMillis,
  /// Closing time, if the session was closed.
  pub closed_at: Option<TimestampMillis>,
  /// External workflow identifier, if any.
  pub workflow_id: Option<String>,
}

/// Generates a ULID for a new message.
#[must_use]
pub fn generate_message_id() -> MessageId {
  ulid::Ulid::generate().to_string()
}

/// Returns the current time as milliseconds since the Unix epoch.
///
/// Returns zero if the system clock is before the epoch.
#[must_use]
pub fn now_millis() -> TimestampMillis {
  SystemTime::now()
    .duration_since(UNIX_EPOCH)
    .map_or(0, |duration| {
      i64::try_from(duration.as_millis()).unwrap_or(i64::MAX)
    })
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn message_kind_round_trips_as_tagged_json() {
    let kind = LogMessageKind::ToolResult {
      tool_call_id: "call-1".to_owned(),
      result: serde_json::json!({"ok": true}),
      is_error: false,
      error_message: None,
    };

    let serialized = serde_json::to_string(&kind).unwrap();
    let restored: LogMessageKind = serde_json::from_str(&serialized).unwrap();

    assert!(matches!(restored, LogMessageKind::ToolResult { .. }));
  }

  #[test]
  fn reasoning_round_trips_all_content_shapes() {
    let reasoning = StoredReasoning {
      id: Some("reasoning-1".to_owned()),
      content: vec![
        StoredReasoningContent::Text {
          text: "analysis".to_owned(),
          signature: Some("signature".to_owned()),
        },
        StoredReasoningContent::Encrypted("ciphertext".to_owned()),
        StoredReasoningContent::Redacted {
          data: "redacted".to_owned(),
        },
        StoredReasoningContent::Summary("summary".to_owned()),
      ],
    };

    let serialized = serde_json::to_string(&reasoning).unwrap();
    let restored: StoredReasoning = serde_json::from_str(&serialized).unwrap();

    assert_eq!(restored.content.len(), 4);
    assert_eq!(restored.id.as_deref(), Some("reasoning-1"));
  }
}
